#!/usr/bin/perl -w

use GD;
use POSIX "strftime";
use Time::gmtime qw(:FIELDS);
use Time::Local;
use LWP::Simple;
use File::Temp "mktemp";
use strict;

my ($new_width,$new_height) = (400,300);

my $url = "http://www.ssec.wisc.edu/data/us_comp/image7.jpg";

# Download the latest image from SSEC
my $tempfile = mktemp("/tmp/weatherXXXXXX");

printf "Downloading weather image as %s\n", $tempfile;

getstore($url,$tempfile) or die "Cannot retreive $url";

my $org_image = GD::Image->newFromJpeg($tempfile);

unlink $tempfile;

print "resizing image\n";

my ($org_width,$org_height) = $org_image->getBounds();

my $new_image = new GD::Image($new_width,$new_height);

$new_image->copyResized($org_image,0,0,0,0,
			$new_width,$new_height,
			$org_width,$org_height);

# Calculate the image time based on the current time.  It appears that
# the images are produced every 1/2 hour and labeled at 15 and 45
# after the hour.  Each image seems to become available about 15
# minutes after its labeled time.
my $org_time = time;
my $gtime = gmtime($org_time);
my $sec_adjust;

if ($gtime->min < 15) {
    $sec_adjust = -900;
}
elsif ($gtime->min < 30) {
    $sec_adjust = 900;
}
elsif ($gtime->min < 45) {
    $sec_adjust = -900;
}
else {
    $sec_adjust = 900;
}

my $new_time = int(($org_time)/1800) * 1800 + $sec_adjust;

$gtime = gmtime($new_time);

my $year = $tm_year+1900;
my $month = $tm_mon + 1;
my $filename = sprintf "/home/inyotech/webapps/ssec/images/image_%4d_%02d_%02d_%02d_%02d.jpg\n", 
    $year,$month,$tm_mday,$tm_hour,$tm_min,$tm_sec;

open JPEG,">$filename" or die "Cannot open output file $filename";

print "saving resized image to $filename\n";

my $jpeg = $new_image->jpeg();

print JPEG $jpeg;




